### ISSUE TITLE
A made up issue to show the use of a manifesto 

### ISSUE THREAD

**Issue by e0ipso** [maintenance-manifesto/maintenance-manifesto.github.io#1]
This issue is only to show that the you can use the manifesto to clarify expectations for everyone.

**Comment by pcambra** [comment]
This is breaking my project so badly. I don't understand how we got here, but this needs to be fixed.

**Comment by e0ipso** [comment]
Hey @pcambra thanks for collaborating in the queue.

This will be prioritized according to the [MAINTENANCE_MANIFESTO.md](https://github.com/maintenance-manifesto/maintenance-manifesto.github.io/issues/1). You can see there how to increase the priority in your issue or sponsor the maintainer to fix it ASAP.

**Comment by pcambra** [comment]
Just for the record, the comment above... @e0ipso made me do it 😂

**Comment by e0ipso** [comment]
It's so out of character for you Pedro, that no one would believe otherwise.
